/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/cartizer.ts
 * Command: astryx theme build src/themes/cartizer.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./cartizer.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const cartizerTheme: DefinedTheme;
